/* 由 tools/download_assets.py 更新图片路径与来源。不要手动把答案写入文件名。 */
window.ASSETS_READY = false;
window.HEROES = [
  {
    "id":"hero_001",
    "nameZh":"D.Va",
    "nameEn":"D.Va",
    "role":"tank",
    "icon":"assets/icons/hero_001.webp",
    "iconFallbacks":[
      "assets/icons/hero_001_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_001.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_001_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/D.Va",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-D.Va.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/19/Icon-D.Va.png/revision/latest?cb=20221005161600",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/1a/OW2_Dva.png/revision/latest?cb=20241108201346",
      "iconFile":"File:Icon-D.Va.png",
      "fullbodyFile":"File:OW2 Dva.png"
    },
    "download":{
      "fandomTitle":"D.Va",
      "iconFile":"Icon-D.Va.png"
    }
  },
  {
    "id":"hero_002",
    "nameZh":"金驭",
    "nameEn":"Domina",
    "role":"tank",
    "icon":"assets/icons/hero_002.webp",
    "iconFallbacks":[
      "assets/icons/hero_002_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_002.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_002_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Domina",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Domina.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/76/Icon-Domina.png/revision/latest?cb=20260210210928",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/d7/OW2_Domina.png/revision/latest?cb=20260213022447",
      "iconFile":"File:Icon-Domina.png",
      "fullbodyFile":"File:OW2 Domina.png"
    },
    "download":{
      "fandomTitle":"Domina",
      "iconFile":"Icon-Domina.png"
    }
  },
  {
    "id":"hero_003",
    "nameZh":"末日铁拳",
    "nameEn":"Doomfist",
    "role":"tank",
    "icon":"assets/icons/hero_003.webp",
    "iconFallbacks":[
      "assets/icons/hero_003_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_003.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_003_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Doomfist",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Doomfist.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/a1/Icon-Doomfist.png/revision/latest?cb=20221005161638",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/1e/OW2_Doomfist_render.png/revision/latest?cb=20241102135923",
      "iconFile":"File:Icon-Doomfist.png",
      "fullbodyFile":"File:OW2 Doomfist render.png"
    },
    "download":{
      "fandomTitle":"Doomfist",
      "iconFile":"Icon-Doomfist.png"
    }
  },
  {
    "id":"hero_004",
    "nameZh":"骇灾",
    "nameEn":"Hazard",
    "role":"tank",
    "icon":"assets/icons/hero_004.webp",
    "iconFallbacks":[
      "assets/icons/hero_004_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_004.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_004_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Hazard",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Hazard.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/54/Icon-Hazard.png/revision/latest?cb=20250211163319",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/6/63/OW2_Hazard.png/revision/latest?cb=20241124152149",
      "iconFile":"File:Icon-Hazard.png",
      "fullbodyFile":"File:OW2 Hazard.png"
    },
    "download":{
      "fandomTitle":"Hazard",
      "iconFile":"Icon-Hazard.png"
    }
  },
  {
    "id":"hero_005",
    "nameZh":"渣客女王",
    "nameEn":"Junker Queen",
    "role":"tank",
    "icon":"assets/icons/hero_005.webp",
    "iconFallbacks":[
      "assets/icons/hero_005_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_005.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_005_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Junker_Queen",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Junker_Queen.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/2b/Icon-Junker_Queen.png/revision/latest?cb=20250426235748",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/50/OW2_JunkerQueen.png/revision/latest?cb=20241101134259",
      "iconFile":"File:Icon-Junker Queen.png",
      "fullbodyFile":"File:OW2 JunkerQueen.png"
    },
    "download":{
      "fandomTitle":"Junker Queen",
      "iconFile":"Icon-Junker Queen.png"
    }
  },
  {
    "id":"hero_006",
    "nameZh":"毛加",
    "nameEn":"Mauga",
    "role":"tank",
    "icon":"assets/icons/hero_006.webp",
    "iconFallbacks":[
      "assets/icons/hero_006_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_006.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_006_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Mauga",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Mauga.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/39/Icon-Mauga.png/revision/latest?cb=20231205235708",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/78/OW2_Mauga.png/revision/latest?cb=20260304093509",
      "iconFile":"File:Icon-Mauga.png",
      "fullbodyFile":"File:OW2 Mauga.png"
    },
    "download":{
      "fandomTitle":"Mauga",
      "iconFile":"Icon-Mauga.png"
    }
  },
  {
    "id":"hero_007",
    "nameZh":"奥丽莎",
    "nameEn":"Orisa",
    "role":"tank",
    "icon":"assets/icons/hero_007.webp",
    "iconFallbacks":[
      "assets/icons/hero_007_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_007.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_007_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Orisa",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Orisa.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/11/Icon-Orisa.png/revision/latest?cb=20221005161652",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/75/OW2-Orisa.png/revision/latest?cb=20241126124432",
      "iconFile":"File:Icon-Orisa.png",
      "fullbodyFile":"File:OW2-Orisa.png"
    },
    "download":{
      "fandomTitle":"Orisa",
      "iconFile":"Icon-Orisa.png"
    }
  },
  {
    "id":"hero_008",
    "nameZh":"拉玛刹",
    "nameEn":"Ramattra",
    "role":"tank",
    "icon":"assets/icons/hero_008.webp",
    "iconFallbacks":[
      "assets/icons/hero_008_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_008.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_008_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Ramattra",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Ramattra.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/6/6f/Icon-Ramattra.png/revision/latest?cb=20221206190323",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/e/ef/OW2_Ramattra.png/revision/latest?cb=20260304093912",
      "iconFile":"File:Icon-Ramattra.png",
      "fullbodyFile":"File:OW2 Ramattra.png"
    },
    "download":{
      "fandomTitle":"Ramattra",
      "iconFile":"Icon-Ramattra.png"
    }
  },
  {
    "id":"hero_009",
    "nameZh":"莱因哈特",
    "nameEn":"Reinhardt",
    "role":"tank",
    "icon":"assets/icons/hero_009.webp",
    "iconFallbacks":[
      "assets/icons/hero_009_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_009.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_009_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Reinhardt",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Reinhardt.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/83/Icon-Reinhardt.png/revision/latest?cb=20221005161659",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/27/OW2_Reinhardt.png/revision/latest?cb=20220409014723",
      "iconFile":"File:Icon-Reinhardt.png",
      "fullbodyFile":"File:OW2 Reinhardt.png"
    },
    "download":{
      "fandomTitle":"Reinhardt",
      "iconFile":"Icon-Reinhardt.png"
    }
  },
  {
    "id":"hero_010",
    "nameZh":"路霸",
    "nameEn":"Roadhog",
    "role":"tank",
    "icon":"assets/icons/hero_010.webp",
    "iconFallbacks":[
      "assets/icons/hero_010_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_010.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_010_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Roadhog",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Roadhog.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/16/Icon-Roadhog.png/revision/latest?cb=20221005161706",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/34/OW2_Roadhog.png/revision/latest?cb=20260213114356",
      "iconFile":"File:Icon-Roadhog.png",
      "fullbodyFile":"File:OW2 Roadhog.png"
    },
    "download":{
      "fandomTitle":"Roadhog",
      "iconFile":"Icon-Roadhog.png"
    }
  },
  {
    "id":"hero_011",
    "nameZh":"西格玛",
    "nameEn":"Sigma",
    "role":"tank",
    "icon":"assets/icons/hero_011.webp",
    "iconFallbacks":[
      "assets/icons/hero_011_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_011.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_011_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Sigma",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Sigma.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/e/e0/Icon-Sigma.png/revision/latest?cb=20221005161714",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/6/60/Galactic_Emperor_Sigma_2.png/revision/latest?cb=20230421192553",
      "iconFile":"File:Icon-Sigma.png",
      "fullbodyFile":"File:Galactic Emperor Sigma 2.png"
    },
    "download":{
      "fandomTitle":"Sigma",
      "iconFile":"Icon-Sigma.png"
    }
  },
  {
    "id":"hero_012",
    "nameZh":"温斯顿",
    "nameEn":"Winston",
    "role":"tank",
    "icon":"assets/icons/hero_012.webp",
    "iconFallbacks":[
      "assets/icons/hero_012_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_012.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_012_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Winston",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Winston.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/f/f8/Icon-Winston.png/revision/latest?cb=20221005161721",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/39/OW2_Winston.png/revision/latest?cb=20241102142153",
      "iconFile":"File:Icon-Winston.png",
      "fullbodyFile":"File:OW2 Winston.png"
    },
    "download":{
      "fandomTitle":"Winston",
      "iconFile":"Icon-Winston.png"
    }
  },
  {
    "id":"hero_013",
    "nameZh":"破坏球",
    "nameEn":"Wrecking Ball",
    "role":"tank",
    "icon":"assets/icons/hero_013.webp",
    "iconFallbacks":[
      "assets/icons/hero_013_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_013.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_013_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Wrecking_Ball",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Wrecking_Ball.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/ca/Icon-Wrecking_Ball.png/revision/latest?cb=20221005161727",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/03/OW2_Wrecking_Ball.png/revision/latest?cb=20260304093441",
      "iconFile":"File:Icon-Wrecking Ball.png",
      "fullbodyFile":"File:OW2 Wrecking Ball.png"
    },
    "download":{
      "fandomTitle":"Wrecking Ball",
      "iconFile":"Icon-Wrecking Ball.png"
    }
  },
  {
    "id":"hero_014",
    "nameZh":"查莉娅",
    "nameEn":"Zarya",
    "role":"tank",
    "icon":"assets/icons/hero_014.webp",
    "iconFallbacks":[
      "assets/icons/hero_014_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_014.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_014_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Zarya",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Zarya.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/75/Icon-Zarya.png/revision/latest?cb=20221005161732",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/02/OW2_Zarya.png/revision/latest?cb=20241108201623",
      "iconFile":"File:Icon-Zarya.png",
      "fullbodyFile":"File:OW2 Zarya.png"
    },
    "download":{
      "fandomTitle":"Zarya",
      "iconFile":"Icon-Zarya.png"
    }
  },
  {
    "id":"hero_015",
    "nameZh":"安燃",
    "nameEn":"Anran",
    "role":"damage",
    "icon":"assets/icons/hero_015.webp",
    "iconFallbacks":[
      "assets/icons/hero_015_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_015.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_015_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Anran",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Anran.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/07/Icon-Anran.png/revision/latest?cb=20260418122337",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/07/OW2_Anran.png/revision/latest?cb=20260611085803",
      "iconFile":"File:Icon-Anran.png",
      "fullbodyFile":"File:OW2 Anran.png"
    },
    "download":{
      "fandomTitle":"Anran",
      "iconFile":"Icon-Anran.png"
    }
  },
  {
    "id":"hero_016",
    "nameZh":"艾什",
    "nameEn":"Ashe",
    "role":"damage",
    "icon":"assets/icons/hero_016.webp",
    "iconFallbacks":[
      "assets/icons/hero_016_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_016.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_016_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Ashe",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Ashe.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/b/be/Icon-Ashe.png/revision/latest?cb=20221005165904",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/89/OW2_Ashe.png/revision/latest?cb=20250329135344",
      "iconFile":"File:Icon-Ashe.png",
      "fullbodyFile":"File:OW2 Ashe.png"
    },
    "download":{
      "fandomTitle":"Ashe",
      "iconFile":"Icon-Ashe.png"
    }
  },
  {
    "id":"hero_017",
    "nameZh":"堡垒",
    "nameEn":"Bastion",
    "role":"damage",
    "icon":"assets/icons/hero_017.webp",
    "iconFallbacks":[
      "assets/icons/hero_017_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_017.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_017_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Bastion",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Bastion.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/51/Icon-Bastion.png/revision/latest?cb=20221005165909",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/4/47/OW2-Bastion.png/revision/latest?cb=20241108201208",
      "iconFile":"File:Icon-Bastion.png",
      "fullbodyFile":"File:OW2-Bastion.png"
    },
    "download":{
      "fandomTitle":"Bastion",
      "iconFile":"Icon-Bastion.png"
    }
  },
  {
    "id":"hero_018",
    "nameZh":"卡西迪",
    "nameEn":"Cassidy",
    "role":"damage",
    "icon":"assets/icons/hero_018.webp",
    "iconFallbacks":[
      "assets/icons/hero_018_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_018.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_018_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Cassidy",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-cassidy.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/5b/Icon-cassidy.png/revision/latest?cb=20221006034952",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/a0/OW2_Cassidy.png/revision/latest?cb=20241108201305",
      "iconFile":"File:Icon-cassidy.png",
      "fullbodyFile":"File:OW2 Cassidy.png"
    },
    "download":{
      "fandomTitle":"Cassidy",
      "iconFile":"Icon-cassidy.png"
    }
  },
  {
    "id":"hero_019",
    "nameZh":"回声",
    "nameEn":"Echo",
    "role":"damage",
    "icon":"assets/icons/hero_019.webp",
    "iconFallbacks":[
      "assets/icons/hero_019_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_019.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_019_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Echo",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Echo.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/d6/Icon-Echo.png/revision/latest?cb=20221005165920",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/b/bd/OW_Echo.png/revision/latest?cb=20241102150435",
      "iconFile":"File:Icon-Echo.png",
      "fullbodyFile":"File:OW Echo.png"
    },
    "download":{
      "fandomTitle":"Echo",
      "iconFile":"Icon-Echo.png"
    }
  },
  {
    "id":"hero_020",
    "nameZh":"埃姆雷",
    "nameEn":"Emre",
    "role":"damage",
    "icon":"assets/icons/hero_020.webp",
    "iconFallbacks":[
      "assets/icons/hero_020_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_020.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_020_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Emre",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Emre.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/34/Icon-Emre.png/revision/latest?cb=20260210210951",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/c7/OW2_Emre.png/revision/latest?cb=20260213003055",
      "iconFile":"File:Icon-Emre.png",
      "fullbodyFile":"File:OW2 Emre.png"
    },
    "download":{
      "fandomTitle":"Emre",
      "iconFile":"Icon-Emre.png"
    }
  },
  {
    "id":"hero_021",
    "nameZh":"弗蕾娅",
    "nameEn":"Freja",
    "role":"damage",
    "icon":"assets/icons/hero_021.webp",
    "iconFallbacks":[
      "assets/icons/hero_021_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_021.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_021_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Freja",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Freja.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/04/Icon-Freja.png/revision/latest?cb=20250422191741",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/31/OW2_Freja.png/revision/latest?cb=20250322151231",
      "iconFile":"File:Icon-Freja.png",
      "fullbodyFile":"File:OW2 Freja.png"
    },
    "download":{
      "fandomTitle":"Freja",
      "iconFile":"Icon-Freja.png"
    }
  },
  {
    "id":"hero_022",
    "nameZh":"源氏",
    "nameEn":"Genji",
    "role":"damage",
    "icon":"assets/icons/hero_022.webp",
    "iconFallbacks":[
      "assets/icons/hero_022_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_022.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_022_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Genji",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Genji.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/1c/Icon-Genji.png/revision/latest?cb=20221005165931",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/17/OW2_Genji.png/revision/latest?cb=20241102133634",
      "iconFile":"File:Icon-Genji.png",
      "fullbodyFile":"File:OW2 Genji.png"
    },
    "download":{
      "fandomTitle":"Genji",
      "iconFile":"Icon-Genji.png"
    }
  },
  {
    "id":"hero_023",
    "nameZh":"半藏",
    "nameEn":"Hanzo",
    "role":"damage",
    "icon":"assets/icons/hero_023.webp",
    "iconFallbacks":[
      "assets/icons/hero_023_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_023.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_023_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Hanzo",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Hanzo.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/71/Icon-Hanzo.png/revision/latest?cb=20221005165925",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/6/66/OW2_Hanzo.png/revision/latest?cb=20260616073741",
      "iconFile":"File:Icon-Hanzo.png",
      "fullbodyFile":"File:OW2 Hanzo.png"
    },
    "download":{
      "fandomTitle":"Hanzo",
      "iconFile":"Icon-Hanzo.png"
    }
  },
  {
    "id":"hero_024",
    "nameZh":"狂鼠",
    "nameEn":"Junkrat",
    "role":"damage",
    "icon":"assets/icons/hero_024.webp",
    "iconFallbacks":[
      "assets/icons/hero_024_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_024.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_024_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Junkrat",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Junkrat.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/9/99/Icon-Junkrat.png/revision/latest?cb=20221005170201",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/f/f2/OW2_Junkrat.png/revision/latest?cb=20260214122743",
      "iconFile":"File:Icon-Junkrat.png",
      "fullbodyFile":"File:OW2 Junkrat.png"
    },
    "download":{
      "fandomTitle":"Junkrat",
      "iconFile":"Icon-Junkrat.png"
    }
  },
  {
    "id":"hero_025",
    "nameZh":"美",
    "nameEn":"Mei",
    "role":"damage",
    "icon":"assets/icons/hero_025.webp",
    "iconFallbacks":[
      "assets/icons/hero_025_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_025.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_025_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Mei",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Mei.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/9/99/Icon-Mei.png/revision/latest?cb=20221005170206",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/7e/OW2_Mei.png/revision/latest?cb=20241102134134",
      "iconFile":"File:Icon-Mei.png",
      "fullbodyFile":"File:OW2 Mei.png"
    },
    "download":{
      "fandomTitle":"Mei",
      "iconFile":"Icon-Mei.png"
    }
  },
  {
    "id":"hero_026",
    "nameZh":"法老之鹰",
    "nameEn":"Pharah",
    "role":"damage",
    "icon":"assets/icons/hero_026.webp",
    "iconFallbacks":[
      "assets/icons/hero_026_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_026.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_026_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Pharah",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Pharah.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/29/Icon-Pharah.png/revision/latest?cb=20221005170211",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/b/b3/OW2_Pharah.png/revision/latest?cb=20241108201144",
      "iconFile":"File:Icon-Pharah.png",
      "fullbodyFile":"File:OW2 Pharah.png"
    },
    "download":{
      "fandomTitle":"Pharah",
      "iconFile":"Icon-Pharah.png"
    }
  },
  {
    "id":"hero_027",
    "nameZh":"死神",
    "nameEn":"Reaper",
    "role":"damage",
    "icon":"assets/icons/hero_027.webp",
    "iconFallbacks":[
      "assets/icons/hero_027_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_027.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_027_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Reaper",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Reaper.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/a9/Icon-Reaper.png/revision/latest?cb=20221005170219",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/8c/OW2_Reaper.png/revision/latest?cb=20241108201455",
      "iconFile":"File:Icon-Reaper.png",
      "fullbodyFile":"File:OW2 Reaper.png"
    },
    "download":{
      "fandomTitle":"Reaper",
      "iconFile":"Icon-Reaper.png"
    }
  },
  {
    "id":"hero_028",
    "nameZh":"死怨",
    "nameEn":"Shion",
    "role":"damage",
    "icon":"assets/icons/hero_028.webp",
    "iconFallbacks":[
      "assets/icons/hero_028_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_028.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_028_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Shion",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Shion.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/74/Icon-Shion.png/revision/latest?cb=20260616181841",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/8a/OW2_Shion.png/revision/latest?cb=20260630073141",
      "iconFile":"File:Icon-Shion.png",
      "fullbodyFile":"File:OW2 Shion.png"
    },
    "download":{
      "fandomTitle":"Shion",
      "iconFile":"Icon-Shion.png"
    }
  },
  {
    "id":"hero_029",
    "nameZh":"西拉",
    "nameEn":"Sierra",
    "role":"damage",
    "icon":"assets/icons/hero_029.webp",
    "iconFallbacks":[
      "assets/icons/hero_029_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_029.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_029_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Sierra",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Sierra.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/32/Icon-Sierra.png/revision/latest?cb=20260414184738",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/1c/OW2_Sierra.png/revision/latest?cb=20260415005653",
      "iconFile":"File:Icon-Sierra.png",
      "fullbodyFile":"File:OW2 Sierra.png"
    },
    "download":{
      "fandomTitle":"Sierra",
      "iconFile":"Icon-Sierra.png"
    }
  },
  {
    "id":"hero_030",
    "nameZh":"索杰恩",
    "nameEn":"Sojourn",
    "role":"damage",
    "icon":"assets/icons/hero_030.webp",
    "iconFallbacks":[
      "assets/icons/hero_030_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_030.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_030_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Sojourn",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Sojourn.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/e/e0/Icon-Sojourn.png/revision/latest?cb=20221005170226",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/ae/OW2_Sojourn.png/revision/latest?cb=20240928162620",
      "iconFile":"File:Icon-Sojourn.png",
      "fullbodyFile":"File:OW2 Sojourn.png"
    },
    "download":{
      "fandomTitle":"Sojourn",
      "iconFile":"Icon-Sojourn.png"
    }
  },
  {
    "id":"hero_031",
    "nameZh":"士兵：76",
    "nameEn":"Soldier: 76",
    "role":"damage",
    "icon":"assets/icons/hero_031.webp",
    "iconFallbacks":[],
    "fullbody":"assets/fullbody/hero_031.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_031_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Soldier:_76",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Soldier_76.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/2b/Icon-Soldier_76.png/revision/latest?cb=20221005170355",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/b/bf/OW2_S76.png/revision/latest?cb=20260208153542",
      "iconFile":"File:Icon-Soldier 76.png",
      "fullbodyFile":"File:OW2 S76.png"
    },
    "download":{
      "fandomTitle":"Soldier: 76",
      "iconFile":"Icon-Soldier 76.png"
    }
  },
  {
    "id":"hero_032",
    "nameZh":"黑影",
    "nameEn":"Sombra",
    "role":"damage",
    "icon":"assets/icons/hero_032.webp",
    "iconFallbacks":[
      "assets/icons/hero_032_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_032.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_032_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Sombra",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Sombra.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/70/Icon-Sombra.png/revision/latest?cb=20221005170556",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/d7/OW2_Sombra.png/revision/latest?cb=20241108201559",
      "iconFile":"File:Icon-Sombra.png",
      "fullbodyFile":"File:OW2 Sombra.png"
    },
    "download":{
      "fandomTitle":"Sombra",
      "iconFile":"Icon-Sombra.png"
    }
  },
  {
    "id":"hero_033",
    "nameZh":"秩序之光",
    "nameEn":"Symmetra",
    "role":"damage",
    "icon":"assets/icons/hero_033.webp",
    "iconFallbacks":[
      "assets/icons/hero_033_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_033.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_033_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Symmetra",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Symmetra.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/06/Icon-Symmetra.png/revision/latest?cb=20221005170604",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/72/OW2-Symmetra.png/revision/latest?cb=20241101134020",
      "iconFile":"File:Icon-Symmetra.png",
      "fullbodyFile":"File:OW2-Symmetra.png"
    },
    "download":{
      "fandomTitle":"Symmetra",
      "iconFile":"Icon-Symmetra.png"
    }
  },
  {
    "id":"hero_034",
    "nameZh":"托比昂",
    "nameEn":"Torbjörn",
    "role":"damage",
    "icon":"assets/icons/hero_034.webp",
    "iconFallbacks":[
      "assets/icons/hero_034_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_034.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_034_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Torbj%C3%B6rn",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Torbj%C3%B6rn.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/ca/Icon-Torbj%C3%B6rn.png/revision/latest?cb=20221005170611",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/d7/OW2_Torbj%C3%B6rn.png/revision/latest?cb=20260321080029",
      "iconFile":"File:Icon-Torbjörn.png",
      "fullbodyFile":"File:OW2 Torbjörn.png"
    },
    "download":{
      "fandomTitle":"Torbjörn",
      "iconFile":"Icon-Torbjörn.png"
    }
  },
  {
    "id":"hero_035",
    "nameZh":"猎空",
    "nameEn":"Tracer",
    "role":"damage",
    "icon":"assets/icons/hero_035.webp",
    "iconFallbacks":[
      "assets/icons/hero_035_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_035.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_035_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Tracer",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Tracer.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/29/Icon-Tracer.png/revision/latest?cb=20221005170620",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/6/63/OW2_Tracer.png/revision/latest?cb=20241102134907",
      "iconFile":"File:Icon-Tracer.png",
      "fullbodyFile":"File:OW2 Tracer.png"
    },
    "download":{
      "fandomTitle":"Tracer",
      "iconFile":"Icon-Tracer.png"
    }
  },
  {
    "id":"hero_036",
    "nameZh":"斩仇",
    "nameEn":"Vendetta",
    "role":"damage",
    "icon":"assets/icons/hero_036.webp",
    "iconFallbacks":[
      "assets/icons/hero_036_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_036.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_036_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Vendetta",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Vendetta.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/dd/Icon-Vendetta.png/revision/latest?cb=20251127231802",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/9/96/OW2_Vendetta.png/revision/latest?cb=20260304090759",
      "iconFile":"File:Icon-Vendetta.png",
      "fullbodyFile":"File:OW2 Vendetta.png"
    },
    "download":{
      "fandomTitle":"Vendetta",
      "iconFile":"Icon-Vendetta.png"
    }
  },
  {
    "id":"hero_037",
    "nameZh":"探奇",
    "nameEn":"Venture",
    "role":"damage",
    "icon":"assets/icons/hero_037.webp",
    "iconFallbacks":[
      "assets/icons/hero_037_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_037.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_037_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Venture",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Venture.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/a0/Icon-Venture.png/revision/latest?cb=20250324005446",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/c7/OW2_Venture.png/revision/latest?cb=20241102122834",
      "iconFile":"File:Icon-Venture.png",
      "fullbodyFile":"File:OW2 Venture.png"
    },
    "download":{
      "fandomTitle":"Venture",
      "iconFile":"Icon-Venture.png"
    }
  },
  {
    "id":"hero_038",
    "nameZh":"黑百合",
    "nameEn":"Widowmaker",
    "role":"damage",
    "icon":"assets/icons/hero_038.webp",
    "iconFallbacks":[
      "assets/icons/hero_038_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_038.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_038_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Widowmaker",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Widowmaker.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/54/Icon-Widowmaker.png/revision/latest?cb=20221005170629",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/ab/OW2_Widowmaker.png/revision/latest?cb=20241108201530",
      "iconFile":"File:Icon-Widowmaker.png",
      "fullbodyFile":"File:OW2 Widowmaker.png"
    },
    "download":{
      "fandomTitle":"Widowmaker",
      "iconFile":"Icon-Widowmaker.png"
    }
  },
  {
    "id":"hero_039",
    "nameZh":"安娜",
    "nameEn":"Ana",
    "role":"support",
    "icon":"assets/icons/hero_039.webp",
    "iconFallbacks":[
      "assets/icons/hero_039_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_039.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_039_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Ana",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Ana.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/3d/Icon-Ana.png/revision/latest?cb=20221005160847",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/5e/OW2_Ana.png/revision/latest?cb=20241102141052",
      "iconFile":"File:Icon-Ana.png",
      "fullbodyFile":"File:OW2 Ana.png"
    },
    "download":{
      "fandomTitle":"Ana",
      "iconFile":"Icon-Ana.png"
    }
  },
  {
    "id":"hero_040",
    "nameZh":"巴蒂斯特",
    "nameEn":"Baptiste",
    "role":"support",
    "icon":"assets/icons/hero_040.webp",
    "iconFallbacks":[
      "assets/icons/hero_040_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_040.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_040_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Baptiste",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Baptiste.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/f/fb/Icon-Baptiste.png/revision/latest?cb=20221005160910",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/00/OW2_Baptiste.png/revision/latest?cb=20241108201237",
      "iconFile":"File:Icon-Baptiste.png",
      "fullbodyFile":"File:OW2 Baptiste.png"
    },
    "download":{
      "fandomTitle":"Baptiste",
      "iconFile":"Icon-Baptiste.png"
    }
  },
  {
    "id":"hero_041",
    "nameZh":"布丽吉塔",
    "nameEn":"Brigitte",
    "role":"support",
    "icon":"assets/icons/hero_041.webp",
    "iconFallbacks":[
      "assets/icons/hero_041_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_041.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_041_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Brigitte",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Brigitte.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/a/a6/Icon-Brigitte.png/revision/latest?cb=20221005160917",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/83/OW2_Brigitte.png/revision/latest?cb=20220930191642",
      "iconFile":"File:Icon-Brigitte.png",
      "fullbodyFile":"File:OW2 Brigitte.png"
    },
    "download":{
      "fandomTitle":"Brigitte",
      "iconFile":"Icon-Brigitte.png"
    }
  },
  {
    "id":"hero_042",
    "nameZh":"伊拉锐",
    "nameEn":"Illari",
    "role":"support",
    "icon":"assets/icons/hero_042.webp",
    "iconFallbacks":[
      "assets/icons/hero_042_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_042.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_042_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Illari",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Illari.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/86/Icon-Illari.png/revision/latest?cb=20230811015354",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/2b/OW2_Illari.png/revision/latest?cb=20260304090158",
      "iconFile":"File:Icon-Illari.png",
      "fullbodyFile":"File:OW2 Illari.png"
    },
    "download":{
      "fandomTitle":"Illari",
      "iconFile":"Icon-Illari.png"
    }
  },
  {
    "id":"hero_043",
    "nameZh":"飞天猫",
    "nameEn":"Jetpack Cat",
    "role":"support",
    "icon":"assets/icons/hero_043.webp",
    "iconFallbacks":[
      "assets/icons/hero_043_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_043.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_043_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Jetpack_Cat",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Jetpack_Cat.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/12/Icon-Jetpack_Cat.png/revision/latest?cb=20260210211110",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/27/OW2_Jetpack_Cat.png/revision/latest?cb=20260206154545",
      "iconFile":"File:Icon-Jetpack Cat.png",
      "fullbodyFile":"File:OW2 Jetpack Cat.png"
    },
    "download":{
      "fandomTitle":"Jetpack Cat",
      "iconFile":"Icon-Jetpack Cat.png"
    }
  },
  {
    "id":"hero_044",
    "nameZh":"朱诺",
    "nameEn":"Juno",
    "role":"support",
    "icon":"assets/icons/hero_044.webp",
    "iconFallbacks":[
      "assets/icons/hero_044_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_044.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_044_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Juno",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Juno.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/c7/Icon-Juno.png/revision/latest?cb=20240822214309",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/2/21/OW2_Juno.png/revision/latest?cb=20260213110336",
      "iconFile":"File:Icon-Juno.png",
      "fullbodyFile":"File:OW2 Juno.png"
    },
    "download":{
      "fandomTitle":"Juno",
      "iconFile":"Icon-Juno.png"
    }
  },
  {
    "id":"hero_045",
    "nameZh":"雾子",
    "nameEn":"Kiriko",
    "role":"support",
    "icon":"assets/icons/hero_045.webp",
    "iconFallbacks":[
      "assets/icons/hero_045_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_045.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_045_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Kiriko",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-kiriko.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/c/ca/Icon-kiriko.png/revision/latest?cb=20221004202610",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/16/OW2_Kiriko.png/revision/latest?cb=20241102132938",
      "iconFile":"File:Icon-kiriko.png",
      "fullbodyFile":"File:OW2 Kiriko.png"
    },
    "download":{
      "fandomTitle":"Kiriko",
      "iconFile":"Icon-kiriko.png"
    }
  },
  {
    "id":"hero_046",
    "nameZh":"生命之梭",
    "nameEn":"Lifeweaver",
    "role":"support",
    "icon":"assets/icons/hero_046.webp",
    "iconFallbacks":[
      "assets/icons/hero_046_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_046.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_046_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Lifeweaver",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Lifeweaver.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/86/Icon-Lifeweaver.png/revision/latest?cb=20230411181321",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/7/7e/OW2_Lifeweaver.png/revision/latest?cb=20241123123936",
      "iconFile":"File:Icon-Lifeweaver.png",
      "fullbodyFile":"File:OW2 Lifeweaver.png"
    },
    "download":{
      "fandomTitle":"Lifeweaver",
      "iconFile":"Icon-Lifeweaver.png"
    }
  },
  {
    "id":"hero_047",
    "nameZh":"卢西奥",
    "nameEn":"Lúcio",
    "role":"support",
    "icon":"assets/icons/hero_047.webp",
    "iconFallbacks":[
      "assets/icons/hero_047_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_047.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_047_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/L%C3%BAcio",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-L%C3%BAcio.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/51/Icon-L%C3%BAcio.png/revision/latest?cb=20221004204914",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/4/44/OW2_L%C3%BAcio.png/revision/latest?cb=20241102140611",
      "iconFile":"File:Icon-Lúcio.png",
      "fullbodyFile":"File:OW2 Lúcio.png"
    },
    "download":{
      "fandomTitle":"Lúcio",
      "iconFile":"Icon-Lúcio.png"
    }
  },
  {
    "id":"hero_048",
    "nameZh":"天使",
    "nameEn":"Mercy",
    "role":"support",
    "icon":"assets/icons/hero_048.webp",
    "iconFallbacks":[
      "assets/icons/hero_048_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_048.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_048_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Mercy",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Mercy.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/0/03/Icon-Mercy.png/revision/latest?cb=20221005160926",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/1/11/OW2_Mercy.png/revision/latest?cb=20241102143122",
      "iconFile":"File:Icon-Mercy.png",
      "fullbodyFile":"File:OW2 Mercy.png"
    },
    "download":{
      "fandomTitle":"Mercy",
      "iconFile":"Icon-Mercy.png"
    }
  },
  {
    "id":"hero_049",
    "nameZh":"瑞稀",
    "nameEn":"Mizuki",
    "role":"support",
    "icon":"assets/icons/hero_049.webp",
    "iconFallbacks":[
      "assets/icons/hero_049_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_049.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_049_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Mizuki",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Mizuki.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/3/36/Icon-Mizuki.png/revision/latest?cb=20260210211030",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/8/83/OW2_Mizuki.png/revision/latest?cb=20260215135742",
      "iconFile":"File:Icon-Mizuki.png",
      "fullbodyFile":"File:OW2 Mizuki.png"
    },
    "download":{
      "fandomTitle":"Mizuki",
      "iconFile":"Icon-Mizuki.png"
    }
  },
  {
    "id":"hero_050",
    "nameZh":"莫伊拉",
    "nameEn":"Moira",
    "role":"support",
    "icon":"assets/icons/hero_050.webp",
    "iconFallbacks":[
      "assets/icons/hero_050_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_050.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_050_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Moira",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Moira.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/55/Icon-Moira.png/revision/latest?cb=20221005160935",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/5/5a/OW2_Moira.png/revision/latest?cb=20240404082150",
      "iconFile":"File:Icon-Moira.png",
      "fullbodyFile":"File:OW2 Moira.png"
    },
    "download":{
      "fandomTitle":"Moira",
      "iconFile":"Icon-Moira.png"
    }
  },
  {
    "id":"hero_051",
    "nameZh":"无漾",
    "nameEn":"Wuyang",
    "role":"support",
    "icon":"assets/icons/hero_051.webp",
    "iconFallbacks":[
      "assets/icons/hero_051_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_051.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_051_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Wuyang",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Wuyang.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/6/6c/Icon-Wuyang.png/revision/latest?cb=20250826195208",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/d/d4/OW2_Wuyang.png/revision/latest?cb=20260305234200",
      "iconFile":"File:Icon-Wuyang.png",
      "fullbodyFile":"File:OW2 Wuyang.png"
    },
    "download":{
      "fandomTitle":"Wuyang",
      "iconFile":"Icon-Wuyang.png"
    }
  },
  {
    "id":"hero_052",
    "nameZh":"禅雅塔",
    "nameEn":"Zenyatta",
    "role":"support",
    "icon":"assets/icons/hero_052.webp",
    "iconFallbacks":[
      "assets/icons/hero_052_b.webp"
    ],
    "fullbody":"assets/fullbody/hero_052.webp",
    "fullbodyFallbacks":[
      "assets/fullbody/hero_052_b.webp"
    ],
    "sources":{
      "heroPage":"https://overwatch.fandom.com/wiki/Zenyatta",
      "overlabPage":"https://overlab.cn/zh/wiki",
      "iconPage":"https://overwatch.fandom.com/wiki/File:Icon-Zenyatta.png",
      "iconImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/f/f7/Icon-Zenyatta.png/revision/latest?cb=20221005160943",
      "fullbodyImage":"https://static.wikia.nocookie.net/overwatch_gamepedia/images/4/44/OW2_Zenyatta.png/revision/latest?cb=20260324055645",
      "iconFile":"File:Icon-Zenyatta.png",
      "fullbodyFile":"File:OW2 Zenyatta.png"
    },
    "download":{
      "fandomTitle":"Zenyatta",
      "iconFile":"Icon-Zenyatta.png"
    }
  }
];
